# Generated by Django 4.0.4 on 2022-05-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='age',
        ),
        migrations.AddField(
            model_name='account',
            name='typeOf',
            field=models.CharField(choices=[('PT', 'student'), ('ST', 'parent'), ('CR', 'curator')], default='PT', max_length=2),
        ),
    ]
