# Generated by Django 4.0.4 on 2022-05-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_account_age_account_typeof'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassChoice', models.CharField(choices=[('PH', 'Physics'), ('CH', 'Chemistry'), ('MA', 'Math'), ('JA', 'Java'), ('PY', 'Python')], max_length=20, unique=True)),
            ],
        ),
    ]
