# Generated by Django 4.0.4 on 2022-05-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_classes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classes',
        ),
        migrations.AddField(
            model_name='account',
            name='ClassChoice',
            field=models.CharField(default=12, max_length=20),
            preserve_default=False,
        ),
    ]
