# Generated by Django 3.2.13 on 2022-05-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='ClassChoice',
            field=models.CharField(max_length=30),
        ),
    ]
