# Generated by Django 3.2.13 on 2022-05-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220524_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='ClassChoice',
        ),
        migrations.AddField(
            model_name='account',
            name='ClassChoice',
            field=models.ManyToManyField(to='users.Classes'),
        ),
    ]
