# Generated by Django 3.2.13 on 2022-05-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20220524_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='attends',
            name='dateAndTime',
            field=models.DateField(auto_now=True, verbose_name='Session date'),
        ),
    ]
