# Generated by Django 3.2.13 on 2022-05-24 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_account_classchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='RegisteredStudents',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
