# Generated by Django 3.2.13 on 2022-05-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20220525_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='classTaught',
        ),
        migrations.AddField(
            model_name='instructor',
            name='classTaught',
            field=models.ManyToManyField(to='users.Classes'),
        ),
    ]
