# Generated by Django 3.2.13 on 2022-05-25 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20220525_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attends',
            name='id',
        ),
        migrations.AlterField(
            model_name='attends',
            name='dateAndTime',
            field=models.DateField(default=datetime.date.today, primary_key=True, serialize=False, verbose_name='Session date'),
        ),
    ]
